# Home Assistant Configuration for DUK Transport
# Konfigurace pro odjezdovou tabuli Dopravy Ústeckého kraje

# Basic Home Assistant configuration
homeassistant:
  name: "Domov"
  latitude: 50.6607  # Ústí nad Labem coordinates
  longitude: 14.0322
  elevation: 218
  unit_system: metric
  currency: CZK
  country: CZ
  time_zone: "Europe/Prague"

# Enable default_config which includes many commonly used integrations
default_config:

# HTTP configuration
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

# Logger configuration for debugging DUK Transport
logger:
  default: info
  logs:
    custom_components.duk_transport: debug

# Template sensors for enhanced display
template:
  - sensor:
      - name: "DUK Transport Next Departure"
        state: >
          {% if states.sensor.duk_transport_zastávka_12345 %}
            {% set next = state_attr('sensor.duk_transport_zastávka_12345', 'next_departure') %}
            {% if next %}
              {{ next.departure_time }}
            {% else %}
              Žádné odjezdy
            {% endif %}
          {% else %}
            Nedostupné
          {% endif %}
        attributes:
          line: >
            {% if states.sensor.duk_transport_zastávka_12345 %}
              {% set next = state_attr('sensor.duk_transport_zastávka_12345', 'next_departure') %}
              {% if next %}{{ next.line }}{% endif %}
            {% endif %}
          destination: >
            {% if states.sensor.duk_transport_zastávka_12345 %}
              {% set next = state_attr('sensor.duk_transport_zastávka_12345', 'next_departure') %}
              {% if next %}{{ next.destination }}{% endif %}
            {% endif %}
          delay: >
            {% if states.sensor.duk_transport_zastávka_12345 %}
              {% set next = state_attr('sensor.duk_transport_zastávka_12345', 'next_departure') %}
              {% if next %}{{ next.delay }}{% endif %}
            {% endif %}

# Automation for notifications about delays
automation:
  - alias: "DUK Transport Delay Notification"
    description: "Upozornění na zpoždění dopravy"
    trigger:
      - platform: state
        entity_id: sensor.duk_transport_zastávka_12345
    condition:
      - condition: template
        value_template: >
          {% set next = state_attr('sensor.duk_transport_zastávka_12345', 'next_departure') %}
          {{ next and next.delay|int > 5 }}
    action:
      - service: persistent_notification.create
        data:
          title: "Zpoždění dopravy"
          message: >
            Linka {{ state_attr('sensor.duk_transport_zastávka_12345', 'next_departure').line }}
            do {{ state_attr('sensor.duk_transport_zastávka_12345', 'next_departure').destination }}
            má zpoždění {{ state_attr('sensor.duk_transport_zastávka_12345', 'next_departure').delay }} minut.

# Input helpers for configuration
input_text:
  duk_stop_id:
    name: "ID zastávky DUK"
    initial: "12345"
    pattern: "[0-9]+"

input_number:
  duk_max_departures:
    name: "Maximální počet odjezdů"
    initial: 10
    min: 1
    max: 20
    step: 1

  duk_update_interval:
    name: "Interval aktualizace (sekundy)"
    initial: 60
    min: 30
    max: 300
    step: 10